### ISSUE TITLE
如何对发送的消息进行鉴权、非法词过滤、限制频率等服务器端扩展？

### ISSUE THREAD

**Issue by qinerg** [ideawu/icomet-demos#6]
如题

**Comment by ideawu** [comment]
根据demo的代码, 以及应用icomet系统的架构图, 你应该在php(web tier)脚本里进行这些业务层的逻辑.

**Comment by qinerg** [comment]
前端是不应该被信任的。
脚本中进行这些业务层的逻辑很容易会被绕过，黑客可以随意推送任意消息，模拟星级用户进行诈骗，可意进行消息轰炸……

**Comment by ideawu** [comment]
在PHP脚本里验证, PHP是后端, 谢谢!

**Comment by qinerg** [comment]
android 直连服务器，它是后端么？

**Comment by qinerg** [comment]
这个软件没有可用性

**Comment by ideawu** [comment]
你脑残蠢蛋, 会不会看图? token不是做验证的吗? 不懂就虚荣心学习!
1. 可配置(而且默认就是)推送消息只能通过PHP(Web Tier), 直接推给icomet是不行的, 所以, 你作为蠢蛋才会说出"黑客可以随意推送任意消息" 这种话来.
2. android 直连 icomet, 必须获取正确的 token 才能连接. 而 token 必须通过 PHP 来获取, 你作为傻逼才会不懂.
3. PHP中你可以做身份验证和权限验证.

![](https://camo.githubusercontent.com/8d094aef1ae6892777503ed7789442d8fe9baf05/687474703a2f2f7777772e6964656177752e636f6d2f69636f6d65742f69636f6d65742d726f6c652e706e673f743d31)

![](https://camo.githubusercontent.com/b7a8e0f4eeb15675025aa51ea531af01e89c09f8/687474703a2f2f7777772e6964656177752e636f6d2f69636f6d65742f69636f6d65742d776f726b666c6f772e706e67)
